# Generated by Django 5.1.3 on 2025-01-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_movies_delete_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='owner',
        ),
        migrations.AddField(
            model_name='movies',
            name='lyrics',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='choosevideo',
            field=models.FileField(default='gh', max_length=60, upload_to='audios'),
            preserve_default=False,
        ),
    ]
