# Generated by Django 5.1.3 on 2025-02-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_remove_playlist_owner_movies_lyrics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='choosevideo',
        ),
        migrations.AddField(
            model_name='playlist',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='file',
            field=models.FileField(default='exit', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='file_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10),
        ),
    ]
