# Generated by Django 5.1.3 on 2024-12-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Songs',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
    ]
