# Generated by Django 5.1.3 on 2024-12-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_rename_song_songs_remove_playlist_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('choosevideo', models.FileField(max_length=60, upload_to='audios')),
            ],
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
